development:
  adapter: postgresql
  encoding: unicode
  database: ticketing_development
  pool: 5
  username: kellywaters
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: ticketing_test
  pool: 5
  username: kellywaters
  password: 